import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { AppStackParamList } from "../../navigation/types";
import { reportService } from "../../services/report.service"; import { nativeFileService } from "../../services/native-file.service"; import { Screen } from "../../components/ui/screen"; import { BackLink } from "../../components/ui/back-link"; import { Card } from "../../components/ui/card"; import { AppButton } from "../../components/ui/button"; import { ErrorBlock, LoadingBlock } from "../../components/ui/states"; import { money } from "../../lib/format"; import { colors } from "../../theme/tokens";
const range = () => {
  const from = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  const to = new Date();
  to.setHours(23, 59, 59, 999);
  return `from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`;
};
export function AnalyticsScreen({navigation}:NativeStackScreenProps<AppStackParamList,"Analytics">){const q=useQuery({queryKey:["reports","daily",range()],queryFn:()=>reportService.daily(range())});if(q.isLoading)return <Screen><Text style={s.title}>Analytics</Text><LoadingBlock/></Screen>;if(q.isError||!q.data)return <Screen><Text style={s.title}>Analytics</Text><ErrorBlock message="Could not load reports." onRetry={()=>void q.refetch()}/></Screen>;const d=q.data;return <Screen><BackLink onPress={()=>navigation.goBack()}/><Text style={s.title}>Analytics</Text><View style={s.metrics}><Metric label="Income" value={money(d.totalIncome)} good/><Metric label="Expenses" value={money(d.totalExpenses)}/></View><Card><Text style={s.label}>NET SAVINGS</Text><Text style={s.big}>{money(d.netSavings)}</Text><Text style={s.sub}>{d.savingsRate}% savings rate · Avg {money(d.averageDailySpending)}/day</Text></Card><Text style={s.heading}>Reports</Text><Link label="Monthly trend" onPress={()=>navigation.navigate("ReportDetail",{kind:"monthly"})}/><Link label="Category breakdown" onPress={()=>navigation.navigate("ReportDetail",{kind:"categories"})}/><Link label="Account breakdown" onPress={()=>navigation.navigate("ReportDetail",{kind:"accounts"})}/><AppButton label="Export CSV" icon="download-outline" outline onPress={async()=>{let file: ReturnType<typeof nativeFileService.saveTextFile>|undefined;try{file=nativeFileService.saveTextFile(`hisaab-report-${new Date().toISOString().slice(0,7)}.csv`,await reportService.exportCsv(range()));await nativeFileService.shareFile(file)}catch(e){Alert.alert("Export failed",e instanceof Error?e.message:"Try again.")}finally{if(file)nativeFileService.cleanupTemporaryFile(file)}}}/></Screen>}
function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <Card style={s.metric}><Text style={s.label}>{label.toUpperCase()}</Text><Text style={[s.value,good&&{color:colors.green}]}>{value}</Text></Card>} function Link({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress}><Card style={s.link}><Text style={s.value}>{label}</Text><Text style={s.sub}>Open report</Text></Card></Pressable>}; const s=StyleSheet.create({title:{color:colors.white,fontSize:29,fontWeight:"900"},metrics:{flexDirection:"row",gap:10},metric:{flex:1,gap:7},label:{color:colors.muted,fontSize:10,fontWeight:"800"},value:{color:colors.white,fontSize:16,fontWeight:"900"},big:{color:colors.white,fontSize:30,fontWeight:"900"},sub:{color:colors.muted,fontSize:12,lineHeight:18},heading:{color:colors.white,fontWeight:"900",fontSize:17},link:{padding:14,gap:4}});
