import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { Investment } from "@hisaab/types";
import { financeService } from "../../services/finance.service";
import type { AppStackParamList } from "../../navigation/types";
import { Screen } from "../../components/ui/screen"; import { BackLink } from "../../components/ui/back-link"; import { Card } from "../../components/ui/card"; import { AppButton } from "../../components/ui/button"; import { Field } from "../../components/ui/field"; import { EmptyBlock, ErrorBlock, LoadingBlock } from "../../components/ui/states"; import { money } from "../../lib/format"; import { colors } from "../../theme/tokens"; import { useState } from "react";
const minor=(v:string)=>Math.round(Number(v)*100); const err=(e:unknown)=>e instanceof Error?e.message:"Try again.";
export function InvestmentListScreen({navigation}:NativeStackScreenProps<AppStackParamList,"Investments">){const q=useQuery({queryKey:["investments"],queryFn:financeService.listInvestments});if(q.isLoading)return <Screen><Text style={s.title}>Investments</Text><LoadingBlock/></Screen>;if(q.isError)return <Screen><Text style={s.title}>Investments</Text><ErrorBlock message="Could not load investments." onRetry={()=>void q.refetch()}/></Screen>;return <Screen><Text style={s.title}>Investments</Text><AppButton label="Add investment" icon="add" onPress={()=>navigation.navigate("CreateInvestment")}/>{q.data?.length ? q.data.map((i)=><Pressable key={i.id} onPress={()=>navigation.navigate("InvestmentDetail",{id:i.id})}><Card style={s.row}><View style={{flex:1}}><Text style={s.name}>{i.name}</Text><Text style={s.sub}>{i.type}{i.detail?` · ${i.detail}`:""}</Text></View><View style={{alignItems:"flex-end"}}><Text style={s.amount}>{money(i.currentMinor,i.currency)}</Text><Text style={[s.sub,{color:i.currentMinor>=i.investedMinor?colors.green:colors.red}]}>{money(i.currentMinor-i.investedMinor,i.currency)} return</Text></View></Card></Pressable>) : <EmptyBlock title="No investments" body="Add a holding to track it."/>}</Screen>}
export function InvestmentDetailScreen({navigation,route}:NativeStackScreenProps<AppStackParamList,"InvestmentDetail">){const q=useQuery({queryKey:["investments"],queryFn:financeService.listInvestments});const c=useQueryClient();const remove=useMutation({mutationFn:()=>financeService.deleteInvestment(route.params.id),onSuccess:async()=>{await c.invalidateQueries({queryKey:["investments"]});navigation.goBack()},onError:e=>Alert.alert("Could not delete",err(e))});const x=q.data?.find(i=>i.id===route.params.id);if(!x)return <Screen><BackLink onPress={()=>navigation.goBack()}/><LoadingBlock/></Screen>;const gain=x.currentMinor-x.investedMinor;const pct=x.investedMinor?Math.round(gain/x.investedMinor*10000)/100:0;return <Screen><BackLink onPress={()=>navigation.goBack()}/><Text style={s.title}>{x.name}</Text><Card style={s.hero}><Text style={s.sub}>{x.type.toUpperCase()}</Text><Text style={s.big}>{money(x.currentMinor,x.currency)}</Text><Text style={[s.sub,{color:gain>=0?colors.green:colors.red}]}>{money(gain,x.currency)} · {pct}%</Text></Card><Card><Text style={s.name}>Invested {money(x.investedMinor,x.currency)}</Text><Text style={s.sub}>{x.detail??"No notes"}</Text></Card><AppButton label="Edit" icon="create-outline" outline onPress={()=>navigation.navigate("EditInvestment",{id:x.id})}/><AppButton label={remove.isPending?"Deleting…":"Delete"} icon="trash-outline" outline onPress={()=>Alert.alert("Delete investment?","This removes the holding.",[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>remove.mutate()}])}/></Screen>}
function InvestmentForm({navigation,id}:{navigation:any;id?:string}){const q=useQuery({queryKey:["investments"],queryFn:financeService.listInvestments,enabled:!!id});const current=q.data?.find(x=>x.id===id);const [name,setName]=useState("");const [type,setType]=useState("");const [invested,setInvested]=useState("");const [value,setValue]=useState("");const [detail,setDetail]=useState("");const c=useQueryClient();const m=useMutation({mutationFn:()=>{const body={name:name||current?.name||"",type:type||current?.type||"",detail:detail||current?.detail||null,investedMinor:minor(invested||String((current?.investedMinor??0)/100)),currentMinor:minor(value||String((current?.currentMinor??0)/100)),sipMinor:current?.sipMinor??0,sipDay:current?.sipDay??null,currency:current?.currency??"INR"};return id?financeService.updateInvestment(id,body):financeService.createInvestment(body)},onSuccess:async()=>{await Promise.all([c.invalidateQueries({queryKey:["investments"]}),c.invalidateQueries({queryKey:["dashboard"]})]);navigation.goBack()},onError:e=>Alert.alert("Could not save",err(e))});if(id&&!current)return <Screen><LoadingBlock/></Screen>;return <Screen><BackLink onPress={()=>navigation.goBack()}/><Text style={s.title}>{id?"Edit investment":"Add investment"}</Text><Field label="Name" placeholder="Holding name" value={name||current?.name||""} onChangeText={setName}/><Field label="Type" placeholder="MF, stock, gold…" value={type||current?.type||""} onChangeText={setType}/><Field label="Invested amount" placeholder="0.00" value={invested||String((current?.investedMinor??0)/100)} onChangeText={setInvested} keyboardType="decimal-pad"/><Field label="Current value" placeholder="0.00" value={value||String((current?.currentMinor??0)/100)} onChangeText={setValue} keyboardType="decimal-pad"/><Field label="Notes" placeholder="Optional" value={detail||current?.detail||""} onChangeText={setDetail}/><AppButton label={m.isPending?"Saving…":"Save investment"} icon="checkmark" onPress={()=>{if(!(name||current?.name)||(minor(invested||String((current?.investedMinor??0)/100))<0))return Alert.alert("Check details","Enter a name and valid amount.");m.mutate()}}/></Screen>}
export function CreateInvestmentScreen(p:NativeStackScreenProps<AppStackParamList,"CreateInvestment">){return <InvestmentForm {...p}/>} export function EditInvestmentScreen({navigation,route}:NativeStackScreenProps<AppStackParamList,"EditInvestment">){return <InvestmentForm navigation={navigation} id={route.params.id}/>}
const s=StyleSheet.create({title:{color:colors.white,fontWeight:"900",fontSize:29},row:{flexDirection:"row",padding:14,gap:10},name:{color:colors.white,fontWeight:"800",fontSize:16},sub:{color:colors.muted,fontSize:12,lineHeight:18},amount:{color:colors.white,fontWeight:"900"},hero:{gap:7,backgroundColor:colors.panel2},big:{color:colors.white,fontSize:31,fontWeight:"900"}});
