import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { computeParticipantShares, majorToMinor, splitExpenseSchema } from "@hisaab/validation";
import type { SplitMethod } from "@hisaab/types";
import { colors } from "../../theme/tokens";
import type { AppStackParamList } from "../../navigation/types";
import { BackLink } from "../../components/ui/back-link";
import { Card } from "../../components/ui/card";
import { AppButton } from "../../components/ui/button";
import { Field } from "../../components/ui/field";
import { ErrorBlock, LoadingBlock } from "../../components/ui/states";
import { localDateKey, money } from "../../lib/format";
import { splitMoneyApi } from "../../features/split-money/api/splitMoneyApi";
import { splitKeys } from "../../features/split-money/api/splitMoneyQueries";

function minorOrZero(value: string) {
  try {
    return majorToMinor(value.replace(/,/g, ""));
  } catch {
    return 0;
  }
}

type Props = NativeStackScreenProps<AppStackParamList, "SplitCreate">;
const STEPS = ["Details", "Who paid", "Split with", "Method", "Reminder", "Review"];
export function SplitCreateScreen({ navigation }: Props) {
  const people = useQuery({ queryKey: splitKeys.people, queryFn: splitMoneyApi.people }); const groups = useQuery({ queryKey: splitKeys.groups, queryFn: splitMoneyApi.groups }); const client = useQueryClient();
  const [step, setStep] = useState(0); const stepRef = useRef(0); stepRef.current = step; const [title,setTitle]=useState(""); const [amount,setAmount]=useState(""); const [category,setCategory]=useState("General"); const [date,setDate]=useState(localDateKey()); const [description,setDescription]=useState(""); const [payerId,setPayerId]=useState<string>(); const [payerIds,setPayerIds]=useState<string[]>([]); const [payerAmounts,setPayerAmounts]=useState<Record<string,string>>({}); const [selected,setSelected]=useState<string[]>([]); const [method,setMethod]=useState<SplitMethod>("equal"); const [shares,setShares]=useState<Record<string,string>>({}); const [items,setItems]=useState<Array<{name:string;quantity:string;amount:string;personIds:string[]}>>([]); const [dueDate,setDueDate]=useState(""); const [reminders,setReminders]=useState(true);
  const total = minorOrZero(amount);
  const itemPayload=items.map(item=>({name:item.name,quantity:Number(item.quantity||1),priceMinor:minorOrZero(item.amount||"0"),kind:"item" as const,personIds:item.personIds})); const participants = useMemo(() => { try { return total && selected.length ? computeParticipantShares({ totalAmountMinor: total, method, participants: selected.map(personId => method==="exact"?{personId,shareAmountMinor:minorOrZero(shares[personId]||"0")}:method==="percentage"?{personId,sharePercentageBps:Math.round(Number(shares[personId]||0)*100)}:method==="shares"?{personId,shareValue:Number(shares[personId]||1)}:{personId}),items:itemPayload }) : []; } catch { return []; } },[total, selected, method, shares, items]);
  const payers=(payerIds.length?payerIds:(payerId?[payerId]:[])).map(id=>({personId:id,paidAmountMinor:minorOrZero(payerAmounts[id]||"0")})); const payerTotal=payers.reduce((sum,p)=>sum+p.paidAmountMinor,0); const allocated=participants.reduce((sum,p)=>sum+p.shareAmountMinor,0); const percentageTotal=selected.reduce((sum,id)=>sum+Number(shares[id]||0),0);
  const create = useMutation({ mutationFn: async () => { if (!payers.length) throw new Error("Choose who paid."); const input = { title, description: description || null, category, totalAmountMinor: total, currency: "INR" as const, expenseDate: date, groupId: null, splitMethod: method, dueDate: dueDate || null, allowPartialPayments: true, sendNotifications: reminders, payers, participants, items:method==="itemwise"?itemPayload:undefined, reminder: reminders ? {enabled:true,channels:["in_app" as const],stopAfterSettlement:true} : undefined }; const parsed=splitExpenseSchema.safeParse(input); if(!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Check the expense details."); return splitMoneyApi.createExpense(parsed.data); }, onSuccess: async e => { await client.invalidateQueries({queryKey:splitKeys.root}); navigation.replace("SplitExpense",{id:e.id}); }, onError:e=>Alert.alert("Could not create split",e instanceof Error?e.message:"Try again.") });
  if (people.isLoading || groups.isLoading) return <View style={styles.fill}><LoadingBlock label="Preparing split…" /></View>; if (people.isError) return <View style={styles.fill}><ErrorBlock message="Could not load people." onRetry={() => void people.refetch()} /></View>;
  const next=()=>{ if(step===0 && (!title.trim() || total<=0 || !date)) return Alert.alert("Check details","Enter a title, positive amount, and date."); if(step===1&&(!payers.length||payerTotal!==total))return Alert.alert("Check contributions",`Payers must contribute exactly ${money(total)}. Current total: ${money(payerTotal)}.`); if(step===2&&!selected.length)return Alert.alert("Choose participants","Select one or more people."); if(step===3&&!participants.length)return Alert.alert("Check split","Exact amounts must equal the total; percentages must equal 100%; shares must be positive."); if(step===3&&method==="itemwise"&&(!itemPayload.length||itemPayload.some(i=>!i.name||i.priceMinor<0||!i.personIds.length)))return Alert.alert("Check items","Each item needs a name, amount, and at least one participant."); setStep(s=>Math.min(5,s+1)); };
  return <View style={styles.fill}><View style={styles.page}><View style={{zIndex:2}}><BackLink onPress={() => { if (stepRef.current) setStep((s) => Math.max(0, s - 1)); else navigation.goBack(); }} label={step ? "Previous step" : "Back"}/><Text style={styles.step}>STEP {step+1} OF 6 · {STEPS[step]}</Text><View style={styles.track}>{STEPS.map((_,i)=><View key={i} style={[styles.dot,i<=step&&styles.dotActive]}/>)}</View></View><ScrollView style={{flex:1}} contentContainerStyle={{gap:13,paddingBottom:16}} keyboardShouldPersistTaps="handled">
    {step===0 && <><Text style={styles.title}>Expense details</Text><Field label="What was this for?" placeholder="Dinner, rent, trip…" value={title} onChangeText={setTitle} autoCapitalize="sentences"/><Field label="Total amount" placeholder="0.00" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Field label="Category" placeholder="General" value={category} onChangeText={setCategory}/><Field label="Expense date (YYYY-MM-DD)" placeholder="2026-10-07" value={date} onChangeText={setDate}/><Field label="Description (optional)" placeholder="Add a note" value={description} onChangeText={setDescription} autoCapitalize="sentences"/></>}
    {step===1 && <><Text style={styles.title}>Who paid?</Text><Text style={styles.sub}>Tap one or more contributors, then enter their original contributions. Total: {money(total)} · Entered: {money(payerTotal)}</Text>{people.data?.map(p=><View key={p.id} style={{gap:6}}><Choice label={p.fullName} selected={payerIds.includes(p.id)||payerId===p.id} onPress={()=>{setPayerId(undefined);setPayerIds(ids=>ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}}/>{(payerIds.includes(p.id)||payerId===p.id)?<Field label={`${p.fullName} paid`} placeholder="0.00" value={payerAmounts[p.id]??""} onChangeText={v=>setPayerAmounts(x=>({...x,[p.id]:v}))} keyboardType="decimal-pad"/>:null}</View>)}</>}
    {step===2 && <><Text style={styles.title}>Split with</Text><Text style={styles.sub}>Select the people who share this expense. Groups can be selected from the Groups screen, then their members added here.</Text>{people.data?.map(p=><Choice key={p.id} label={p.fullName} selected={selected.includes(p.id)} onPress={()=>setSelected(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/>)}</>}
    {step===3 && <><Text style={styles.title}>How should it be split?</Text>{(["equal","exact","percentage","shares","itemwise"] as SplitMethod[]).map(m=><Choice key={m} label={m === "itemwise" ? "Item-wise" : m[0]!.toUpperCase()+m.slice(1)} selected={method===m} onPress={()=>setMethod(m)}/>) }{method==="itemwise"?<><AppButton label="Add item" icon="add" outline onPress={()=>setItems(x=>[...x,{name:"",quantity:"1",amount:"",personIds:[...selected]}])}/>{items.map((item,index)=><Card key={index} style={styles.review}><Field label="Item name" placeholder="Dinner" value={item.name} onChangeText={v=>setItems(x=>x.map((a,i)=>i===index?{...a,name:v}:a))}/><Field label="Quantity" placeholder="1" value={item.quantity} onChangeText={v=>setItems(x=>x.map((a,i)=>i===index?{...a,quantity:v}:a))} keyboardType="number-pad"/><Field label="Item amount" placeholder="0.00" value={item.amount} onChangeText={v=>setItems(x=>x.map((a,i)=>i===index?{...a,amount:v}:a))} keyboardType="decimal-pad"/><Text style={styles.sub}>Assigned participants</Text>{selected.map(id=><Choice key={id} label={people.data?.find(p=>p.id===id)?.fullName??"Participant"} selected={item.personIds.includes(id)} onPress={()=>setItems(x=>x.map((a,i)=>i===index?{...a,personIds:a.personIds.includes(id)?a.personIds.filter(p=>p!==id):[...a.personIds,id]}:a))}/>) }<AppButton label="Remove item" icon="trash-outline" outline onPress={()=>setItems(x=>x.filter((_,i)=>i!==index))}/></Card>) }<Text style={styles.sub}>Item allocation preview: {participants.map(p=>`${people.data?.find(x=>x.id===p.personId)?.fullName??"Person"} ${money(p.shareAmountMinor)}`).join(" · ")}</Text></>:method!=="equal"?<><Text style={styles.sub}>{method==="exact"?"Enter amounts. They must equal the total.":method==="percentage"?"Enter percentages. They must equal 100%.":"Enter positive share weights."}</Text>{selected.map(id=><Field key={id} label={people.data?.find(p=>p.id===id)?.fullName??"Participant"} placeholder={method==="exact"?"0.00":method==="percentage"?"0": "1"} value={shares[id]??""} onChangeText={v=>setShares(x=>({...x,[id]:v}))} keyboardType="decimal-pad"/>) }<Card style={styles.review}><Text style={styles.sub}>Total {money(total)} · Allocated {money(allocated)}</Text>{method==="percentage"?<Text style={styles.sub}>Percentage total: {percentageTotal}%</Text>:null}<Text style={[styles.sub,{color:allocated>total?colors.red:colors.green}]}>{allocated>total?`Overallocated ${money(allocated-total)}`:`Remaining ${money(total-allocated)}`}</Text><Text style={styles.sub}>Preview: {participants.map(p=>`${people.data?.find(x=>x.id===p.personId)?.fullName??"Person"} ${money(p.shareAmountMinor)}`).join(" · ")}</Text></Card></>:null}</>}
    {step===4 && <><Text style={styles.title}>Due date & reminder</Text><Field label="Due date (optional)" placeholder="YYYY-MM-DD" value={dueDate} onChangeText={setDueDate}/><Choice label="Send in-app reminder" selected={reminders} onPress={()=>setReminders(!reminders)}/><Text style={styles.sub}>The current endpoint supports in-app, email, WhatsApp, and SMS channels. This app only enables in-app reminders because delivery capability is not exposed by the mobile config.</Text></>}
    {step===5 && <><Text style={styles.title}>Review split</Text><Card style={styles.review}><Text style={styles.reviewTitle}>{title}</Text><Text style={styles.total}>{money(total)}</Text><Text style={styles.sub}>{category} · {date} · {method}</Text><Text style={styles.sub}>{participants.length} participant(s), {payers.length ? `${payers.length} payer(s)` : "no payer"}</Text>{participants.map(p=><Text key={p.personId} style={styles.sub}>{people.data?.find(x=>x.id===p.personId)?.fullName ?? "Participant"}: {money(p.shareAmountMinor)}</Text>)}</Card></>}
    </ScrollView><View style={styles.bottom}><AppButton label={step===5?(create.isPending?"Creating…":"Create split"):"Continue"} onPress={()=>{ if (step === 5) { if (!create.isPending) create.mutate(); } else next(); }} /></View>
  </View></View>;
}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.choice,selected&&styles.choiceSelected]}><Text style={[styles.choiceText,selected&&styles.choiceTextSelected]}>{label}</Text><Text style={{color:selected?colors.ink:colors.green}}>{selected?"Selected":"Select"}</Text></Pressable>}
const styles=StyleSheet.create({fill:{flex:1,backgroundColor:colors.bg},page:{padding:18,gap:13,flex:1},step:{color:colors.green,fontSize:11,fontWeight:"900",letterSpacing:.8},track:{flexDirection:"row",gap:5},dot:{height:5,flex:1,borderRadius:4,backgroundColor:colors.line},dotActive:{backgroundColor:colors.green},title:{color:colors.white,fontSize:27,fontWeight:"900"},sub:{color:colors.muted,fontSize:12,lineHeight:18},choice:{padding:15,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.panel,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},choiceSelected:{backgroundColor:colors.green,borderColor:colors.green},choiceText:{color:colors.white,fontWeight:"800"},choiceTextSelected:{color:colors.ink},bottom:{marginTop:"auto",paddingTop:4},review:{gap:9},reviewTitle:{color:colors.white,fontSize:18,fontWeight:"900"},total:{color:colors.green,fontWeight:"900",fontSize:28}});
