import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { colors } from "../../theme/tokens";
import type { AppStackParamList } from "../../navigation/types";
import { BackLink } from "../../components/ui/back-link";
import { Card } from "../../components/ui/card";
import { AppButton } from "../../components/ui/button";
import { Field } from "../../components/ui/field";
import { ErrorBlock, LoadingBlock } from "../../components/ui/states";
import { money } from "../../lib/format";
import { splitMoneyApi } from "../../features/split-money/api/splitMoneyApi";
import { splitKeys } from "../../features/split-money/api/splitMoneyQueries";

export function SplitPeopleScreen({ navigation }: NativeStackScreenProps<AppStackParamList, "SplitPeople">) {
  const people = useQuery({ queryKey: splitKeys.people, queryFn: splitMoneyApi.people });
  const [name, setName] = useState(""); const client = useQueryClient();
  const create = useMutation({ mutationFn: () => splitMoneyApi.createPerson({ fullName: name, countryCode: "IN", email: null, relationship: "friend" }), onSuccess: async () => { setName(""); await client.invalidateQueries({ queryKey: splitKeys.people }); }, onError: e => Alert.alert("Could not add person", e instanceof Error ? e.message : "Try again.") });
  return <Directory title="People" onBack={() => navigation.goBack()} loading={people.isLoading} error={people.isError} retry={() => void people.refetch()}>
    <Card style={styles.form}><Field label="Add person" placeholder="Full name" value={name} onChangeText={setName} autoCapitalize="words"/><AppButton label={create.isPending ? "Adding…" : "Add person"} icon="person-add-outline" onPress={() => { if (name.trim() && !create.isPending) create.mutate(); }}/></Card>
    {people.data?.map(p => <Pressable key={p.id} onPress={()=>navigation.navigate("SplitPersonDetail",{id:p.id})}><Card style={styles.row}><Avatar name={p.fullName}/><View><Text style={styles.name}>{p.fullName}</Text><Text style={styles.muted}>{p.relationship}{p.email ? ` · ${p.email}` : ""}</Text></View></Card></Pressable>)}
  </Directory>;
}
export function SplitGroupsScreen({ navigation }: NativeStackScreenProps<AppStackParamList, "SplitGroups">) {
  const groups = useQuery({ queryKey: splitKeys.groups, queryFn: splitMoneyApi.groups });
  const [name, setName] = useState(""); const client = useQueryClient();
  const create = useMutation({ mutationFn: () => splitMoneyApi.createGroup({ name, description: null, category: null, imageUrl: null, memberPersonIds: [], groupType: "shared", currency: "INR", defaultSplitMethod: "equal", defaultDueDays: 7, allowMemberAdd: true, allowMemberEdit: true, allowMemberSettle: true, sendNotifications: true }), onSuccess: async () => { setName(""); await client.invalidateQueries({ queryKey: splitKeys.groups }); }, onError: e => Alert.alert("Could not create group", e instanceof Error ? e.message : "Try again.") });
  return <Directory title="Groups" onBack={() => navigation.goBack()} loading={groups.isLoading} error={groups.isError} retry={() => void groups.refetch()}>
    <Card style={styles.form}><Field label="Create group" placeholder="Trip, home, family…" value={name} onChangeText={setName} autoCapitalize="words"/><AppButton label={create.isPending ? "Creating…" : "Create group"} icon="add-circle-outline" onPress={() => { if (name.trim() && !create.isPending) create.mutate(); }}/></Card>
    {groups.data?.map(g => <Pressable key={g.id} onPress={()=>navigation.navigate("SplitGroupDetail",{id:g.id})}><Card style={styles.row}><Avatar name={g.name}/><View><Text style={styles.name}>{g.name}</Text><Text style={styles.muted}>{g.members?.length ?? 0} members · {g.defaultSplitMethod}</Text></View></Card></Pressable>)}
  </Directory>;
}
export function SplitHistoryScreen({ navigation }: NativeStackScreenProps<AppStackParamList, "SplitHistory">) {
  const history = useQuery({ queryKey: splitKeys.history, queryFn: splitMoneyApi.history });
  return <Directory title="Split history" onBack={() => navigation.goBack()} loading={history.isLoading} error={history.isError} retry={() => void history.refetch()}>
    {history.data?.expenses.map(e => <Pressable key={e.id} onPress={() => navigation.navigate("SplitExpense", { id: e.id })}><Card style={styles.row}><View style={{ flex: 1 }}><Text style={styles.name}>{e.title}</Text><Text style={styles.muted}>{e.expenseDate} · {e.status.replaceAll("_", " ")}</Text></View><Text style={styles.name}>{(e.totalAmountMinor / 100).toFixed(2)}</Text></Card></Pressable>)}
  </Directory>;
}
export function SplitPersonDetailScreen({navigation,route}:NativeStackScreenProps<AppStackParamList,"SplitPersonDetail">){const q=useQuery({queryKey:["split","person",route.params.id],queryFn:()=>splitMoneyApi.person(route.params.id)});const client=useQueryClient();const [fullName,setFullName]=useState("");const [phone,setPhone]=useState("");const [email,setEmail]=useState("");const save=useMutation({mutationFn:()=>splitMoneyApi.updatePerson(route.params.id,{fullName:fullName||q.data!.person.fullName,phone:phone||null,email:email||null}),onSuccess:async()=>{await Promise.all([client.invalidateQueries({queryKey:splitKeys.people}),client.invalidateQueries({queryKey:["split","person",route.params.id]}),client.invalidateQueries({queryKey:splitKeys.root})]);await q.refetch()},onError:e=>Alert.alert("Could not save",e instanceof Error?e.message:"Try again.")});return <Directory title="Person" onBack={()=>navigation.goBack()} loading={q.isLoading} error={q.isError} retry={()=>void q.refetch()}>{q.data?<><Card><Text style={styles.name}>{q.data.person.fullName}</Text><Text style={styles.muted}>{q.data.person.relationship}{q.data.person.phone?` · ${q.data.person.phone}`:""}{q.data.person.email?` · ${q.data.person.email}`:""}{` · You are owed ${money(q.data.youAreOwedMinor)} · You owe ${money(q.data.youOweMinor)}`}</Text></Card><Field label="Name" placeholder="Full name" value={fullName||q.data.person.fullName} onChangeText={setFullName}/><Field label="Phone" placeholder="Optional" value={phone||q.data.person.phone||""} onChangeText={setPhone}/><Field label="Email" placeholder="Optional" value={email||q.data.person.email||""} onChangeText={setEmail}/><AppButton label={save.isPending?"Saving…":"Save person"} icon="checkmark" onPress={()=>{if(!(fullName||q.data!.person.fullName).trim())return Alert.alert("Check details","Name is required.");save.mutate()}}/><Text style={styles.muted}>Balances above come from this person's shared expenses.</Text></>:null}</Directory>}
export function SplitGroupDetailScreen({navigation,route}:NativeStackScreenProps<AppStackParamList,"SplitGroupDetail">){const q=useQuery({queryKey:["split","group",route.params.id],queryFn:()=>splitMoneyApi.group(route.params.id)});const people=useQuery({queryKey:splitKeys.people,queryFn:splitMoneyApi.people});const client=useQueryClient();const [name,setName]=useState("");const refresh=async()=>{await client.invalidateQueries({queryKey:splitKeys.groups});await q.refetch()};const save=useMutation({mutationFn:()=>splitMoneyApi.updateGroup(route.params.id,{name:name||q.data!.name}),onSuccess:refresh,onError:e=>Alert.alert("Could not save",e instanceof Error?e.message:"Try again.")});const add=useMutation({mutationFn:(personId:string)=>splitMoneyApi.addGroupMember(route.params.id,personId),onSuccess:refresh,onError:e=>Alert.alert("Could not add member",e instanceof Error?e.message:"Try again.")});const remove=useMutation({mutationFn:(memberId:string)=>splitMoneyApi.removeGroupMember(route.params.id,memberId),onSuccess:refresh,onError:e=>Alert.alert("Could not remove member",e instanceof Error?e.message:"Try again.")});return <Directory title="Group" onBack={()=>navigation.goBack()} loading={q.isLoading} error={q.isError} retry={()=>void q.refetch()}>{q.data?<><Card><Text style={styles.name}>{q.data.name}</Text><Text style={styles.muted}>{q.data.description??"No description"}</Text></Card><Field label="Group name" placeholder="Group name" value={name||q.data.name} onChangeText={setName}/><AppButton label={save.isPending?"Saving…":"Save group"} icon="checkmark" onPress={()=>save.mutate()}/><Text style={styles.name}>Members</Text>{q.data.members?.map(m=><Card key={m.id} style={styles.row}><Avatar name={m.person?.fullName??"Member"}/><View style={{flex:1}}><Text style={styles.name}>{m.person?.fullName??"Member"}</Text></View><Pressable disabled={remove.isPending} onPress={()=>Alert.alert("Remove member?",`Remove ${m.person?.fullName??"this member"} from the group?`,[{text:"Cancel",style:"cancel"},{text:"Remove",style:"destructive",onPress:()=>remove.mutate(m.id)}])}><Text style={{color:colors.red,fontWeight:"800"}}>{remove.isPending?"Removing…":"Remove"}</Text></Pressable></Card>)}<Text style={styles.name}>Add member</Text>{people.data?.filter(p=>!q.data!.members?.some(m=>m.personId===p.id)).map(p=><AppButton key={p.id} label={add.isPending?"Adding…":`Add ${p.fullName}`} icon="person-add-outline" outline onPress={()=>{if(!add.isPending)add.mutate(p.id)}}/>)}<Text style={styles.name}>Expenses</Text>{q.data.expenses?.map(e=><Pressable key={e.id} onPress={()=>navigation.navigate("SplitExpense",{id:e.id})}><Card><Text style={styles.name}>{e.title}</Text><Text style={styles.muted}>{e.status.replaceAll("_"," ")}</Text></Card></Pressable>)}</>:null}</Directory>}
function Avatar({ name }: { name: string }) { return <View style={styles.avatar}><Text style={styles.avatarText}>{name.slice(0, 1).toUpperCase()}</Text></View>; }
function Directory({ title, onBack, loading, error, retry, children }: { title: string; onBack: () => void; loading: boolean; error: boolean; retry: () => void; children: ReactNode }) { return <ScrollView style={styles.fill} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><BackLink onPress={onBack}/><Text style={styles.title}>{title}</Text>{loading ? <LoadingBlock/> : error ? <ErrorBlock message={`Could not load ${title.toLowerCase()}.`} onRetry={retry}/> : children}</ScrollView>; }
const styles = StyleSheet.create({ fill: { flex: 1, backgroundColor: colors.bg }, page: { padding: 18, gap: 12 }, title: { color: colors.white, fontSize: 29, fontWeight: "900" }, form: { gap: 12 }, row: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14 }, avatar: { height: 38, width: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: colors.green }, avatarText: { color: colors.ink, fontWeight: "900" }, name: { color: colors.white, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 12 } });
