import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { accountSchema, majorToMinor } from "@hisaab/validation";
import type { Account } from "@hisaab/types";
import { colors } from "../../theme/tokens";
import type { AppStackParamList } from "../../navigation/types";
import { accountService } from "../../services/account.service";
import { transactionService } from "../../services/transaction.service";
import { BackLink } from "../../components/ui/back-link";
import { Card } from "../../components/ui/card";
import { AppButton } from "../../components/ui/button";
import { Field } from "../../components/ui/field";
import { EmptyBlock, ErrorBlock, LoadingBlock } from "../../components/ui/states";
import { money } from "../../lib/format";

export function AccountsScreen({ navigation }: NativeStackScreenProps<AppStackParamList, "Accounts">) {
  const client = useQueryClient(); const accounts = useQuery({ queryKey: ["accounts"], queryFn: accountService.list }); const catalog = useQuery({ queryKey: ["account-catalog"], queryFn: accountService.catalog });
  const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [institutionName, setInstitution] = useState(""); const [opening, setOpening] = useState(""); const [type, setType] = useState("BANK");
  const create = useMutation({ mutationFn: () => { const openingBalanceMinor = majorToMinor(opening || "0"); const parsed = accountSchema.safeParse({ name, type, institutionName: institutionName || null, openingBalanceMinor, currency: "INR", isActive: true }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Check account details."); return accountService.createBank(parsed.data); }, onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["accounts"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); setCreating(false); setName(""); setInstitution(""); setOpening(""); }, onError: e => Alert.alert("Could not create account", e instanceof Error ? e.message : "Try again.") });
  if (accounts.isLoading) return <View style={styles.fill}><LoadingBlock /></View>; if (accounts.isError) return <View style={styles.fill}><ErrorBlock message="Could not load accounts." onRetry={() => void accounts.refetch()} /></View>;
  return <ScrollView style={styles.fill} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><BackLink onPress={() => navigation.goBack()}/><Text style={styles.title}>Accounts</Text><AppButton label={creating ? "Close form" : "Add bank account"} icon="add-circle-outline" onPress={() => setCreating(v => !v)}/>{creating ? <Card style={styles.form}><Field label="Account name" placeholder="Primary savings" value={name} onChangeText={setName}/><Field label="Bank / institution" placeholder="Your bank" value={institutionName} onChangeText={setInstitution}/><Field label="Opening balance" placeholder="0.00" value={opening} onChangeText={setOpening} keyboardType="decimal-pad"/><Text style={styles.label}>TYPE</Text><View style={styles.chips}>{(catalog.data ?? []).map(item => <Pressable key={item.type} onPress={() => setType(item.type)} style={[styles.chip, type === item.type && styles.active]}><Text style={styles.chipText}>{item.name}</Text></Pressable>)}</View><AppButton label={create.isPending ? "Saving…" : "Create bank account"} onPress={() => { if (create.isPending) return; if (type !== "BANK") return Alert.alert("Bank accounts only", "Cash, UPI, and card accounts come from the Hisaab catalog. Add a bank here."); if (!name.trim() || !institutionName.trim()) return Alert.alert("Check account details", "Account name and bank are required."); create.mutate(); }}/></Card> : null}{accounts.data?.length ? accounts.data.map(item => <Pressable key={item.id} onPress={() => navigation.navigate("AccountDetail", { id: item.id })}><Card style={styles.row}><View style={{ flex: 1 }}><Text style={styles.name}>{item.name}</Text><Text style={styles.muted}>{item.type}{item.institutionName ? ` · ${item.institutionName}` : ""}</Text></View><Text style={styles.amount}>{money(item.currentBalanceMinor, item.currency)}</Text></Card></Pressable>) : <EmptyBlock title="No accounts" body="Add a bank account to track balances."/>}</ScrollView>;
}
export function AccountDetailScreen({ navigation, route }: NativeStackScreenProps<AppStackParamList, "AccountDetail">) {
  const client = useQueryClient(); const account = useQuery({ queryKey: ["account", route.params.id], queryFn: () => accountService.get(route.params.id) }); const history = useQuery({ queryKey: ["transactions", "account", route.params.id], queryFn: async () => (await transactionService.list(new URLSearchParams({ account_id: route.params.id, limit: "20", sort: "newest" }).toString())).data }); const [editing, setEditing] = useState(false); const [name, setName] = useState(""); const [institution, setInstitution] = useState("");
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["accounts"] }), client.invalidateQueries({ queryKey: ["account", route.params.id] }), client.invalidateQueries({ queryKey: ["transactions"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); };
  const update = useMutation({ mutationFn: () => accountService.update(route.params.id, { name, institutionName: institution || null }), onSuccess: async () => { await refresh(); setEditing(false); }, onError: e => Alert.alert("Could not update account", e instanceof Error ? e.message : "Try again.") }); const archive = useMutation({ mutationFn: () => accountService.archive(route.params.id), onSuccess: async () => { await refresh(); navigation.goBack(); }, onError: e => Alert.alert("Could not archive account", e instanceof Error ? e.message : "Try again.") });
  if (account.isLoading) return <View style={styles.fill}><LoadingBlock /></View>; if (!account.data) return <View style={styles.fill}><ErrorBlock message="Could not load account." onRetry={() => void account.refetch()} /></View>; const item = account.data;
  return <ScrollView style={styles.fill} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><BackLink onPress={() => navigation.goBack()}/><Text style={styles.title}>{item.name}</Text><Card style={styles.summary}><Text style={styles.label}>{item.type}</Text><Text style={styles.big}>{money(item.currentBalanceMinor, item.currency)}</Text><Text style={styles.muted}>{item.institutionName ?? "No institution"} · opened {item.createdAt.slice(0, 10)}</Text></Card>{editing ? <Card style={styles.form}><Field label="Name" placeholder="Account name" value={name} onChangeText={setName}/><Field label="Institution" placeholder="Bank" value={institution} onChangeText={setInstitution}/><AppButton label={update.isPending ? "Saving…" : "Save account"} onPress={() => { if (!update.isPending) update.mutate(); }}/></Card> : <><AppButton label="Edit account" icon="create-outline" onPress={() => { setName(item.name); setInstitution(item.institutionName ?? ""); setEditing(true); }}/><AppButton label={archive.isPending ? "Archiving…" : "Archive account"} outline icon="archive-outline" onPress={() => Alert.alert("Archive account?", "It will no longer be available for new transactions.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => archive.mutate() }])}/></>}<Text style={styles.label}>RECENT TRANSACTIONS</Text>{history.isLoading ? <LoadingBlock/> : history.data?.length ? history.data.map(tx => <Card key={tx.id} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.name}>{tx.merchant ?? tx.categoryName ?? "Transaction"}</Text><Text style={styles.muted}>{tx.transactionAt.slice(0, 10)}</Text></View><Text style={styles.amount}>{money(tx.amountMinor, tx.currency)}</Text></Card>) : <EmptyBlock title="No transactions"/>}</ScrollView>;
}
const styles = StyleSheet.create({ fill: { flex: 1, backgroundColor: colors.bg }, page: { padding: 18, gap: 12 }, title: { color: colors.white, fontSize: 29, fontWeight: "900" }, form: { gap: 12 }, label: { color: colors.muted, fontWeight: "900", fontSize: 10, letterSpacing: .7 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, chip: { borderWidth: 1, borderColor: colors.line, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 8 }, active: { backgroundColor: colors.green, borderColor: colors.green }, chipText: { color: colors.white, fontSize: 11, fontWeight: "800" }, row: { flexDirection: "row", alignItems: "center", padding: 14, gap: 10 }, name: { color: colors.white, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 12 }, amount: { color: colors.white, fontWeight: "900" }, summary: { gap: 7, backgroundColor: colors.panel2 }, big: { color: colors.green, fontSize: 31, fontWeight: "900" } });
