import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { goalContributionSchema, goalSchema, majorToMinor } from "@hisaab/validation";
import type { GoalContribution, SavingsGoal } from "@hisaab/types";
import { goalService } from "../../services/goal.service";
import { BackLink } from "../../components/ui/back-link";
import { AppButton } from "../../components/ui/button";
import { Card } from "../../components/ui/card";
import { Field } from "../../components/ui/field";
import { EmptyBlock, ErrorBlock, LoadingBlock } from "../../components/ui/states";
import { useSingleFlight } from "../../lib/single-flight";
import { money } from "../../lib/format";
import { colors } from "../../theme/tokens";

const refresh = (client: ReturnType<typeof useQueryClient>) => Promise.all(["goals", "goal-contributions", "dashboard"].map((key) => client.invalidateQueries({ queryKey: [key] })));
export function GoalsListScreen({ navigation }: any) { const goals = useQuery({ queryKey: ["goals"], queryFn: goalService.list }); if (goals.isLoading) return <Page><LoadingBlock /></Page>; if (goals.isError) return <Page><ErrorBlock message="Could not load goals." onRetry={() => void goals.refetch()} /></Page>; const visible = goals.data?.filter((goal) => goal.isActive !== false) ?? []; return <Page><Title text="Savings goals" navigation={navigation} /><AppButton label="Create goal" onPress={() => navigation.navigate("CreateGoal")} />{visible.length ? visible.map((goal) => <GoalCard key={goal.id} goal={goal} onPress={() => navigation.navigate("GoalDetail", { id: goal.id })} />) : <EmptyBlock title="No savings goals" body="Create a goal to start saving." />}</Page>; }
function GoalCard({ goal, onPress }: { goal: SavingsGoal; onPress: () => void }) { const pct = Math.min(100, Math.round((goal.savedAmountMinor / goal.targetAmountMinor) * 100)); return <Pressable onPress={onPress}><Card style={styles.row}><View style={{ flex: 1 }}><Text style={styles.name}>{goal.icon} {goal.name}</Text><Text style={styles.muted}>{money(goal.savedAmountMinor, goal.currency)} of {money(goal.targetAmountMinor, goal.currency)}</Text><Text style={styles.muted}>{goal.targetDate ? `Target ${goal.targetDate}` : "No target date"}</Text></View><Text style={styles.amount}>{pct}%</Text></Card></Pressable>; }
export function GoalDetailScreen({ navigation, route }: any) { const client = useQueryClient(); const goals = useQuery({ queryKey: ["goals"], queryFn: goalService.list }); const contributions = useQuery({ queryKey: ["goal-contributions"], queryFn: goalService.contributions }); const archive = useMutation({ mutationFn: () => goalService.update(route.params.id, { isActive: false }), onSuccess: () => refresh(client).then(() => navigation.goBack()), onError: error("Could not archive goal") }); const goal = goals.data?.find((item) => item.id === route.params.id); if (goals.isLoading) return <Page><LoadingBlock /></Page>; if (!goal) return <Page><ErrorBlock message="Goal was not found." onRetry={() => void goals.refetch()} /></Page>; const remaining = Math.max(0, goal.targetAmountMinor - goal.savedAmountMinor); return <Page><Title text={goal.name} navigation={navigation} /><Card style={styles.summary}><Text style={styles.big}>{money(goal.savedAmountMinor, goal.currency)}</Text><Text style={styles.muted}>of {money(goal.targetAmountMinor, goal.currency)} · {money(remaining, goal.currency)} remaining</Text><Text style={styles.muted}>{goal.targetDate ? `Target date: ${goal.targetDate}` : "No target date"}</Text></Card><AppButton label="Add contribution" onPress={() => navigation.navigate("GoalContribution", { id: goal.id })} /><AppButton outline label="Edit goal" onPress={() => navigation.navigate("EditGoal", { id: goal.id })} /><AppButton outline label={archive.isPending ? "Archiving…" : "Archive goal"} onPress={() => { if (archive.isPending) return; Alert.alert("Archive goal?", "It will leave your active goals list.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => { if (!archive.isPending) archive.mutate(); } }]); }} /><Text style={styles.label}>RECENT CONTRIBUTIONS</Text>{contributions.data?.filter((item) => item.goalId === goal.id).slice(0, 3).map((item) => <ContributionRow key={item.id} item={item} />)}<AppButton outline label="View contribution history" onPress={() => navigation.navigate("ContributionHistory", { id: goal.id })} /></Page>; }
export function CreateGoalScreen({ navigation }: any) { return <GoalForm navigation={navigation} />; }
export function EditGoalScreen({ navigation, route }: any) { return <GoalForm navigation={navigation} id={route.params.id} />; }
function GoalForm({ navigation, id }: { navigation: any; id?: string }) { const client = useQueryClient(); const goals = useQuery({ queryKey: ["goals"], queryFn: goalService.list }); const old = goals.data?.find((item) => item.id === id); const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [date, setDate] = useState(""); const [hydrated, setHydrated] = useState(!id); useEffect(() => { if (!id || !old || hydrated) return; setName(old.name); setAmount(String(old.targetAmountMinor / 100)); setDate(old.targetDate ?? ""); setHydrated(true); }, [id, old, hydrated]); const save = useMutation({ mutationFn: () => { const parsed = goalSchema.safeParse({ name, icon: old?.icon ?? "*", targetAmountMinor: majorToMinor(amount), currency: old?.currency ?? "INR", targetDate: date || null, notes: old?.notes ?? null }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Check the goal values."); return id ? goalService.update(id, parsed.data) : goalService.create(parsed.data); }, onSuccess: () => refresh(client).then(() => navigation.goBack()), onError: error("Could not save goal") }); return <Page><Title text={id ? "Edit goal" : "New goal"} navigation={navigation} /><Card style={styles.form}><Field label="Goal name" placeholder="Emergency fund" value={name} onChangeText={setName} /><Field label="Target amount" placeholder="0.00" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /><Field label="Target date (YYYY-MM-DD)" placeholder="2027-01-01" value={date} onChangeText={setDate} /><AppButton label={save.isPending ? "Saving…" : "Save goal"} onPress={() => { if (save.isPending || (id && !hydrated)) return; if (!name.trim() || !amount.trim()) return Alert.alert("Check the goal", "Name and target amount are required."); save.mutate(); }} /></Card></Page>; }
export function GoalContributionScreen({ navigation, route }: any) { const client = useQueryClient(); const [amount, setAmount] = useState(""); const [notes, setNotes] = useState(""); const flight = useSingleFlight(); const add = useMutation({ mutationFn: () => { const parsed = goalContributionSchema.safeParse({ amountMinor: majorToMinor(amount), notes: notes || null }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Check the contribution."); return goalService.contribute(route.params.id, parsed.data); }, onSuccess: () => refresh(client).then(() => navigation.goBack()), onError: error("Could not add contribution"), onSettled: () => flight.end() }); return <Page><Title text="Add contribution" navigation={navigation} /><Card style={styles.form}><Field label="Amount" placeholder="0.00" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /><Field label="Note" placeholder="Optional" value={notes} onChangeText={setNotes} /><AppButton label={add.isPending ? "Adding…" : "Add contribution"} disabled={add.isPending} onPress={() => flight.run(add.isPending, () => add.mutate())} /></Card></Page>; }
export function ContributionHistoryScreen({ navigation, route }: any) { const q = useQuery({ queryKey: ["goal-contributions"], queryFn: goalService.contributions }); if (q.isLoading) return <Page><LoadingBlock /></Page>; if (q.isError) return <Page><ErrorBlock message="Could not load contributions." onRetry={() => void q.refetch()} /></Page>; const rows = q.data?.filter((item) => item.goalId === route.params.id) ?? []; return <Page><Title text="Contribution history" navigation={navigation} />{rows.length ? rows.map((item) => <ContributionRow key={item.id} item={item} />) : <EmptyBlock title="No contributions yet" />}</Page>; }
function ContributionRow({ item }: { item: GoalContribution }) { return <Card style={styles.row}><View style={{ flex: 1 }}><Text style={styles.name}>{item.goalName ?? "Contribution"}</Text><Text style={styles.muted}>{item.contributedAt.slice(0, 10)}{item.notes ? ` · ${item.notes}` : ""}</Text></View><Text style={styles.amount}>{money(item.amountMinor)}</Text></Card>; }
function Title({ text, navigation }: { text: string; navigation: any }) { return <><BackLink onPress={() => navigation.goBack()} /><Text style={styles.title}>{text}</Text></>; } function Page({ children }: { children: React.ReactNode }) { return <ScrollView style={styles.fill} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">{children}</ScrollView>; } function error(title: string) { return (e: unknown) => Alert.alert(title, e instanceof Error ? e.message : "Try again."); }
const styles = StyleSheet.create({ fill: { flex: 1, backgroundColor: colors.bg }, page: { padding: 18, gap: 12 }, title: { color: colors.white, fontSize: 29, fontWeight: "900" }, row: { flexDirection: "row", gap: 10, padding: 14 }, name: { color: colors.white, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 12 }, amount: { color: colors.green, fontWeight: "900" }, summary: { gap: 7, backgroundColor: colors.panel2 }, big: { color: colors.green, fontSize: 32, fontWeight: "900" }, form: { gap: 12 }, label: { color: colors.muted, fontSize: 10, fontWeight: "900" } });
